<?php

namespace ContainerSwefIcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GVB8IWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gVB_8IW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gVB_8IW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'intervention' => ['privates', '.errored..service_locator.gVB_8IW.App\\Entity\\Intervention', NULL, 'Cannot autowire service ".service_locator.gVB_8IW": it needs an instance of "App\\Entity\\Intervention" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'intervention' => 'App\\Entity\\Intervention',
            'entityManager' => '?',
        ]);
    }
}
