<?php

namespace ContainerSwefIcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AYsh93hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AYsh93h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AYsh93h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'instrument' => ['privates', '.errored..service_locator.AYsh93h.App\\Entity\\Instrument', NULL, 'Cannot autowire service ".service_locator.AYsh93h": it needs an instance of "App\\Entity\\Instrument" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'instrument' => 'App\\Entity\\Instrument',
            'entityManager' => '?',
        ]);
    }
}
