<?php

namespace ContainerSwefIcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstrumentControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AYsh93h.App\Controller\InstrumentController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.AYsh93h'] ?? $container->load('get_ServiceLocator_AYsh93hService'));

        if (isset($container->privates['.service_locator.AYsh93h.App\\Controller\\InstrumentController::edit()'])) {
            return $container->privates['.service_locator.AYsh93h.App\\Controller\\InstrumentController::edit()'];
        }

        return $container->privates['.service_locator.AYsh93h.App\\Controller\\InstrumentController::edit()'] = $a->withContext('App\\Controller\\InstrumentController::edit()', $container);
    }
}
