<?php

namespace ContainerSwefIcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInterventionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WhoyZJQ.App\Entity\Intervention' shared service.
     *
     * @return \App\Entity\Intervention
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.WhoyZJQ": it needs an instance of "App\\Entity\\Intervention" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
