<?php

namespace ContainerSwefIcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInterventionControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gVB_8IW.App\Controller\InterventionController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gVB_8IW.App\\Controller\\InterventionController::delete()'] = ($container->privates['.service_locator.gVB_8IW'] ?? $container->load('get_ServiceLocator_GVB8IWService'))->withContext('App\\Controller\\InterventionController::delete()', $container);
    }
}
