<?php

namespace ContainerSwefIcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInterventionControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MVxzEdn.App\Controller\InterventionController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MVxzEdn.App\\Controller\\InterventionController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'interventionRepository' => ['privates', 'App\\Repository\\InterventionRepository', 'getInterventionRepositoryService', true],
        ], [
            'interventionRepository' => 'App\\Repository\\InterventionRepository',
        ]))->withContext('App\\Controller\\InterventionController::index()', $container);
    }
}
