<?php

namespace ContainerSwefIcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInterventionControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WhoyZJQ.App\Controller\InterventionController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WhoyZJQ.App\\Controller\\InterventionController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'intervention' => ['privates', '.errored..service_locator.WhoyZJQ.App\\Entity\\Intervention', NULL, 'Cannot autowire service ".service_locator.WhoyZJQ": it needs an instance of "App\\Entity\\Intervention" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'intervention' => 'App\\Entity\\Intervention',
        ]))->withContext('App\\Controller\\InterventionController::show()', $container);
    }
}
