<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Professionnel extends \App\Entity\Professionnel implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cpos' => [parent::class, 'cpos', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'interventions' => [parent::class, 'interventions', null, 16],
        "\0".parent::class."\0".'mail' => [parent::class, 'mail', null, 16],
        "\0".parent::class."\0".'metier' => [parent::class, 'metier', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'numRue' => [parent::class, 'numRue', null, 16],
        "\0".parent::class."\0".'rue' => [parent::class, 'rue', null, 16],
        "\0".parent::class."\0".'tel' => [parent::class, 'tel', null, 16],
        "\0".parent::class."\0".'ville' => [parent::class, 'ville', null, 16],
        'cpos' => [parent::class, 'cpos', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'interventions' => [parent::class, 'interventions', null, 16],
        'mail' => [parent::class, 'mail', null, 16],
        'metier' => [parent::class, 'metier', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'numRue' => [parent::class, 'numRue', null, 16],
        'rue' => [parent::class, 'rue', null, 16],
        'tel' => [parent::class, 'tel', null, 16],
        'ville' => [parent::class, 'ville', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
