<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Instrument extends \App\Entity\Instrument implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cheminImage' => [parent::class, 'cheminImage', null, 16],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'dateAchat' => [parent::class, 'dateAchat', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'idAccessoire' => [parent::class, 'idAccessoire', null, 16],
        "\0".parent::class."\0".'idContratPret' => [parent::class, 'idContratPret', null, 16],
        "\0".parent::class."\0".'idCouleur' => [parent::class, 'idCouleur', null, 16],
        "\0".parent::class."\0".'idIntervention' => [parent::class, 'idIntervention', null, 16],
        "\0".parent::class."\0".'marque' => [parent::class, 'marque', null, 16],
        "\0".parent::class."\0".'numSerie' => [parent::class, 'numSerie', null, 16],
        "\0".parent::class."\0".'prixAchat' => [parent::class, 'prixAchat', null, 16],
        "\0".parent::class."\0".'typeInstrument' => [parent::class, 'typeInstrument', null, 16],
        "\0".parent::class."\0".'utilisation' => [parent::class, 'utilisation', null, 16],
        'cheminImage' => [parent::class, 'cheminImage', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'dateAchat' => [parent::class, 'dateAchat', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'idAccessoire' => [parent::class, 'idAccessoire', null, 16],
        'idContratPret' => [parent::class, 'idContratPret', null, 16],
        'idCouleur' => [parent::class, 'idCouleur', null, 16],
        'idIntervention' => [parent::class, 'idIntervention', null, 16],
        'marque' => [parent::class, 'marque', null, 16],
        'numSerie' => [parent::class, 'numSerie', null, 16],
        'prixAchat' => [parent::class, 'prixAchat', null, 16],
        'typeInstrument' => [parent::class, 'typeInstrument', null, 16],
        'utilisation' => [parent::class, 'utilisation', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
