<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TypeInstrument extends \App\Entity\TypeInstrument implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'classeInstrument' => [parent::class, 'classeInstrument', null, 16],
        "\0".parent::class."\0".'cours' => [parent::class, 'cours', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'idProfesseur' => [parent::class, 'idProfesseur', null, 16],
        "\0".parent::class."\0".'instruments' => [parent::class, 'instruments', null, 16],
        "\0".parent::class."\0".'libelle' => [parent::class, 'libelle', null, 16],
        'classeInstrument' => [parent::class, 'classeInstrument', null, 16],
        'cours' => [parent::class, 'cours', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'idProfesseur' => [parent::class, 'idProfesseur', null, 16],
        'instruments' => [parent::class, 'instruments', null, 16],
        'libelle' => [parent::class, 'libelle', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
