<?php

namespace ContainerFPCLjF3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LN10zhaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lN10zha' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lN10zha'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\InstrumentController::index' => ['privates', '.service_locator.9sOGoae.App\\Controller\\InstrumentController::index()', 'getInstrumentControllerindexService', true],
            'App\\Controller\\InstrumentController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\InstrumentController::new()', 'getInstrumentControllernewService', true],
            'App\\Controller\\InstrumentController::show' => ['privates', '.service_locator.19UqbJR.App\\Controller\\InstrumentController::show()', 'getInstrumentControllershowService', true],
            'App\\Controller\\InstrumentController::edit' => ['privates', '.service_locator.AYsh93h.App\\Controller\\InstrumentController::edit()', 'getInstrumentControllereditService', true],
            'App\\Controller\\InstrumentController::delete' => ['privates', '.service_locator.AYsh93h.App\\Controller\\InstrumentController::delete()', 'getInstrumentControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\InstrumentController:index' => ['privates', '.service_locator.9sOGoae.App\\Controller\\InstrumentController::index()', 'getInstrumentControllerindexService', true],
            'App\\Controller\\InstrumentController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\InstrumentController::new()', 'getInstrumentControllernewService', true],
            'App\\Controller\\InstrumentController:show' => ['privates', '.service_locator.19UqbJR.App\\Controller\\InstrumentController::show()', 'getInstrumentControllershowService', true],
            'App\\Controller\\InstrumentController:edit' => ['privates', '.service_locator.AYsh93h.App\\Controller\\InstrumentController::edit()', 'getInstrumentControllereditService', true],
            'App\\Controller\\InstrumentController:delete' => ['privates', '.service_locator.AYsh93h.App\\Controller\\InstrumentController::delete()', 'getInstrumentControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\InstrumentController::index' => '?',
            'App\\Controller\\InstrumentController::new' => '?',
            'App\\Controller\\InstrumentController::show' => '?',
            'App\\Controller\\InstrumentController::edit' => '?',
            'App\\Controller\\InstrumentController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\InstrumentController:index' => '?',
            'App\\Controller\\InstrumentController:new' => '?',
            'App\\Controller\\InstrumentController:show' => '?',
            'App\\Controller\\InstrumentController:edit' => '?',
            'App\\Controller\\InstrumentController:delete' => '?',
        ]);
    }
}
