<?php

namespace ContainerFPCLjF3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstrumentControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.19UqbJR.App\Controller\InstrumentController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.19UqbJR.App\\Controller\\InstrumentController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'instrument' => ['privates', '.errored..service_locator.19UqbJR.App\\Entity\\Instrument', NULL, 'Cannot autowire service ".service_locator.19UqbJR": it needs an instance of "App\\Entity\\Instrument" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'instrument' => 'App\\Entity\\Instrument',
        ]))->withContext('App\\Controller\\InstrumentController::show()', $container);
    }
}
