<?php

namespace ContainerFPCLjF3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstrumentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.19UqbJR.App\Entity\Instrument' shared service.
     *
     * @return \App\Entity\Instrument
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.19UqbJR": it needs an instance of "App\\Entity\\Instrument" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
