<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4te5cRo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4te5cRo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4te5cRo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4te5cRo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4te5cRo\App_KernelDevDebugContainer([
    'container.build_hash' => '4te5cRo',
    'container.build_id' => '9dc3d4c7',
    'container.build_time' => 1763986508,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4te5cRo');
