<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHlH7ojL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHlH7ojL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHlH7ojL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHlH7ojL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHlH7ojL\App_KernelDevDebugContainer([
    'container.build_hash' => 'HlH7ojL',
    'container.build_id' => '08bf278d',
    'container.build_time' => 1762336394,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHlH7ojL');
