<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS8h1KNr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS8h1KNr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS8h1KNr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS8h1KNr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS8h1KNr\App_KernelDevDebugContainer([
    'container.build_hash' => 'S8h1KNr',
    'container.build_id' => '519b2a51',
    'container.build_time' => 1762339246,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS8h1KNr');
